services:
  app:
    build: .
    container_name: simple-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: demo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
